# Generated by Django 5.0 on 2023-12-07 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='ticket',
            new_name='count',
        ),
    ]
